import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import styles from '../../styles/Home.module.css'
import words from '../../models/words'

export default () => {
  const router = useRouter()
  const goBack = () => router.back()
  return (
    <div className={styles.container}>
      <Head>
        <title>Happy armenian alphabet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {router.query.letter}
        </h1>
        <ul>
          {words[router.query.letter as string]?.map((couple) => <li key={couple.word}>{couple.word}: {couple.translation}</li>)}
        </ul>
        <span onClick={goBack}>Back</span>
      </main>

      <footer className={styles.footer}>
        @Maksimushquee
      </footer>
    </div>
  )
}
