import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { div, h1, main, meta, title, link } from 'react-dom'

import styles from '../styles/Home.module.css'
import Letter from '../components/letter'


import lettersArray from '../models/letters'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Happy armenian alphabet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Let's speak armenian!
        </h1>
        <div className={styles.grid}>
          { 
            lettersArray.map((letter, index) => (
              <div key={`letter${letter.likeEng}`} className={styles.card}>
                <Letter {...{...letter, tabIndex: index}} />
              </div>
            ))
          }
        </div>
      </main>

      <footer className={styles.footer}>
        @Maksimushquee
      </footer>
    </div>
  )
}
