export default [{ capital: 'Ա', small: 'ա', likeEng: 'ask', url: '/sounds/armenian_alphabet_a.mp3'},
{ capital: 'Բ', small: 'բ', likeEng: 'by, phone', url: '/sounds/armenian_alphabet_b.mp3'},
{ capital: 'Գ', small: 'գ', likeEng: 'go, ok', url: '/sounds/armenian_alphabet_g.mp3'},
{ capital: 'Դ', small: 'դ', likeEng: 'do, thin', url: '/sounds/armenian_alphabet_d.mp3'},
{ capital: 'Ե', small: 'ե', likeEng: 'yes', url: '/sounds/armenian_alphabet_y.mp3'},
{ capital: 'Զ', small: 'զ', likeEng: 'zoo', url: '/sounds/armenian_alphabet_z.mp3'},
{ capital: 'Է', small: 'է', likeEng: 'egg', url: '/sounds/armenian_alphabet_e.mp3'},
{ capital: 'Ը', small: 'ը', likeEng: 'put', url: '/sounds/armenian_alphabet_ee.mp3'},
{ capital: 'Թ', small: 'թ', likeEng: 'time', url: '/sounds/armenian_alphabet_th.mp3'},
{ capital: 'Ժ', small: 'ժ', likeEng: 'vision', url: '/sounds/armenian_alphabet_j.mp3'},
{ capital: 'Ի', small: 'ի', likeEng: 'innk', url: '/sounds/armenian_alphabet_i.mp3'},
{ capital: 'Լ', small: 'լ', likeEng: 'love', url: '/sounds/armenian_alphabet_l.mp3'},
{ capital: 'Խ', small: 'խ', likeEng: 'Bach', url: '/sounds/armenian_alphabet_kh.mp3'},
{ capital: 'Ծ', small: 'ծ', likeEng: 'cats', url: '/sounds/armenian_alphabet_ts.mp3'},
{ capital: 'Կ', small: 'կ', likeEng: 'ok, go', url: '/sounds/armenian_alphabet_k.mp3'},
{ capital: 'Հ', small: 'հ', likeEng: 'hi', url: '/sounds/armenian_alphabet_h.mp3'},
{ capital: 'Ձ', small: 'ձ', likeEng: 'kids', url: '/sounds/armenian_alphabet_dz.mp3'},
{ capital: 'Ղ', small: 'ղ', likeEng: 'merci', url: '/sounds/armenian_alphabet_gh.mp3'},
{ capital: 'Ճ', small: 'ճ', likeEng: 'urge', url: '/sounds/armenian_alphabet_tsh.mp3'},
{ capital: 'Մ', small: 'մ', likeEng: 'mom', url: '/sounds/armenian_alphabet_m.mp3'},
{ capital: 'Յ', small: 'յ', likeEng: 'you', url: '/sounds/armenian_alphabet_ye.mp3'},
{ capital: 'Ն', small: 'ն', likeEng: 'nice', url: '/sounds/armenian_alphabet_n.mp3'},
{ capital: 'Շ', small: 'շ', likeEng: 'shiny', url: '/sounds/armenian_alphabet_sh.mp3'},
{ capital: 'Ո', small: 'ո', likeEng: 'vast, pot', url: '/sounds/armenian_alphabet_v.mp3'},
{ capital: 'Չ', small: 'չ', likeEng: 'porch', url: '/sounds/armenian_alphabet_tch.mp3'},
{ capital: 'Պ', small: 'պ', likeEng: 'pen, by', url: '/sounds/armenian_alphabet_p.mp3'},
{ capital: 'Ջ', small: 'ջ', likeEng: 'job', url: '/sounds/armenian_alphabet_dj.mp3'},
{ capital: 'Ռ', small: 'ռ', likeEng: 'Roma', url: '/sounds/armenian_alphabet_r.mp3'},
{ capital: 'Ս', small: 'ս', likeEng: 'sand', url: '/sounds/armenian_alphabet_s.mp3'},
{ capital: 'Վ', small: 'վ', likeEng: 'vast', url: '/sounds/armenian_alphabet_ve.mp3'},
{ capital: 'Տ', small: 'տ', likeEng: 'but', url: '/sounds/armenian_alphabet_t.mp3'},
{ capital: 'Ր', small: 'ր', likeEng: 'red', url: '/sounds/armenian_alphabet_ze.mp3'},
{ capital: 'Ց', small: 'ց', likeEng: 'bits', url: '/sounds/armenian_alphabet_tse.mp3'},
{ capital: 'Ւ', small: 'ւ', likeEng: 'cool', url: '/sounds/armenian_alphabet_u.mp3'},
{ capital: 'Փ', small: 'փ', likeEng: 'pear', url: '/sounds/armenian_alphabet_ph.mp3'},
{ capital: 'Ք', small: 'ք', likeEng: 'king', url: '/sounds/armenian_alphabet_khe.mp3'},
{ capital: 'Օ', small: 'օ', likeEng: 'old', url: '/sounds/armenian_alphabet_o.mp3'},
{ capital: 'Ֆ', small: 'ֆ', likeEng: 'fly', url: '/sounds/armenian_alphabet_vee.mp3'},
{ capital: 'ՈՒ', small: 'ու', likeEng: 'tool', url: '/sounds/armenian_alphabet_u.mp3'},
{ capital: 'և', small: 'և', likeEng: 'Yevett', url: '/sounds/armenian_alphabet_yev.mp3'}]
